name: Android Build CI

on:
  push:
    branches:
      - main # Puedes ajustar el nombre de la rama según tu configuración
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3

      - name: Cache Haxelib
        uses: actions/cache@v2
        with:
          path: ${{ env.HAXELIB_ROOT }}
          key: haxelib-${{ runner.os }}

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v2.0.2

      - name: Set Up Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set Up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r15c

      - name: Install Dependencies
        run: |
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install hxcpp --quiet
          haxelib run lime setup flixel
          haxelib remove flixel-addons --quiet
          haxelib run lime setup
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install hscript --quiet
          haxelib install hxCodec
          haxelib install newgrounds 1.4.0 --quiet
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib git polymod https://github.com/larsiusprime/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git extension-webm https://github.com/luckydog7/extension-webm --quiet
          haxelib git linc_luajit https://github.com/MasterEric/linc_luajit.git --quiet
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit.git --quiet
          haxelib install actuate

      - name: Build APK
        run: haxelib run lime build android -Dci

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Android Build
          path: export/release/android/bin/app/build/outputs/apk/debug
